#!/bin/dash

black=#11111B
green=#ABE9B3
white=#D9E0EE
grey=#282737
blue=#96CDFB
orange=#fab387
yellow=#F9E2AF
red=#F28FAD
darkblue=#83BAE8
mauve=#cba6f7
lavender=#b4befe
interval=0
base=#1e1e2e



pkg_updates() {
  updates=$({ timeout 20 checkupdates 2>/dev/null || true; } | wc -l)

  if [ -z "$updates" ]; then
    printf "^b$red^^c$black^  ^b$black^^c$red^ Fully Updated"
  else
    printf "^b$red^^c$black^  ^b$black^^c$red^ $updates"" updates"
  fi
}

cpu() { 
  cpu_val=$(grep -o "^[^ ]*" /proc/loadavg) 

  printf "^c$black^ ^b$orange^ "
  printf "^c$orange^ ^b$black^ $cpu_val"
}

mem() {
    printf "^c$black^^b$yellow^  "
    printf "^c$yellow^^b$black^ $(free -h | awk '/^Mem/ { print $3 }' | sed s/i//g)"
}

clock() {
	printf "^c$black^ ^b$green^ 󱑆 "
	printf "^c$green^^b$black^ $(date '+%H:%M')"
	printf "^c$black^ ^b$blue^ 󰸗 "
	printf "^c$blue^^b$black^ $(date '+%d/%m/%Y')"
	printf "^c$black^ ^b$mauve^ W "
	printf "^c$mauve^^b$black^ $(date '+%V')  "
}


while true; do

	sleep 5
    [ $interval = 0 ] || [ $(($interval % 3600)) = 0 ] && updates=$(pkg_updates)
    interval=$((interval + 1))

		dwm -s "$updates $(cpu) $(mem)$(clock)"
done &


